
== Can I add annotations on axioms?

* OWL allows annotation of axioms, for provenance for example
* Tawny provides a syntax for this
* Annotates `SubClassOf` axiom between `Man` and `Person` with a comment.
* http://www.russet.org.uk/blog/3028

[source,lisp]
----
(defclass Man
 :super
 (annotate Person
           (owl-comment "States that every man is a person")))
----

ifndef::backend-slidy[]
[NOTE]
====
One of the reasons for the complexity of the OWL API is that it allows
annotations to be passed in lots of places, including on the axioms that
assert the relationship between, for example, two classes. One simplification
I made with Tawny is to hide this complexity. Moreover, Tawny is frame-centric
so the axioms are not normally seen explicitly.

Unfortunately, it appears that in hiding the complexity, I had also hidden a
capability that people actually use: GO uses axiom annotations for provenance
for instance. So I have added this capability into tawny with a slightly
expanded syntax.

The `annotate` function returns an object encapsulating and OWL API entity and
an annotation that will be added to the axiom of the frame. We can see this in
the example given. Note that we are annotating neither `Person` nor `Man` in
this case, but the relationship between them.
====
endif::backend-slidy[]

== How does this affect ontology deployment

* Potentially none -- Tawny generates an OWL file
* Potentially automatable
** In project source, or through leiningen plugin
* Or can publish as a maven artefact
** Ontology can be downloaded as a software artefact
** Separates out ontology identifier and download location

ifndef::backend-slidy[]
[NOTE]
====
We can deploy ontologies to bioportal or to anywhere else exactly as we do
now. Save the OWL file, and do stuff to it manually.

Of course, in a programmable environment, it is also very easy to add
additional deployment technology -- so generate one or more files, copy them
to another location, via ssh or http, check them in somewhere. This can be
achieved either in the project source or as a leiningen plugin.

Or, finally, we can deploy our ontology like any other piece of Clojure code,
as a maven artefact, to maven central, to clojars (like maven central but for
Clojure), or to our own private repo. This also separates our the ontology
identifier from the download location. It's possible to argue whether this is
a good thing or a bad thing.
====
endif::backend-slidy[]


== How do you version your ontology?

* Tawny-OWL uses a line-orientated syntax
* You edit *source code* not a visualisation of an XML file
* Like various OBO flat file syntaxes, it works well in git or any VCS
* Leiningen supports release versioning, using Semantic Versioning

ifndef::backend-slidy[]
[NOTE]
====
Tawny-OWL uses a line-orientated syntax and what you edit is source code, not
some XML that has been generated. So, it works very well with version control.
The serialisation order is entirely predictable because there is no
serialisation -- it's source code, it only changes if you edit it.

Working with source code also means that diff tools show you changes in the
same form of the code that you edit, so it's very easy to compare two
versions, two branches what ever. The only exception to this are the EDN files
used for numeric IDs of OBO identifiers. These have been designed to version
well (they are generated but not regeneratable, so should be regarded a source
code), but only time will tell. "They do not version well" will be considered
to be a bug though, and will be something I would want to fix.

We've used git for all the various ontologies we have developed, and it works
nicely. Actually "nicely" is an understatement. The move to modern version
management, rather than anything bespoke build just for ontologies makes an
enormous difference. For my money, it's reason to move to tawny all by itself.

It is also possible to version in the sense of release tagged versions of an
ontology and to use a dependency mechanism.
====
endif::backend-slidy[]

== How do you test your ontology

* Clojure supports one or more unit tests frameworks
* We use the default (core.test) framework
* Tawny-OWL provides some fixtures
* Also use spreadsheet generated testing
** Paper – http://arxiv.org/abs/1505.04112
** Tawny-Karyotype – http://github.com/jaydchan/tawny-karyotype
** Plain English Summary - http://www.russet.org.uk/blog/3074


ifndef::backend-slidy[]
[NOTE]
====
We test our ontologies explicitly and sometimes very heavily. Tawny-OWL
provides some fixtures to make this easy and we use `core.test` but there
other test frameworks and we might move at some point. This has been written
up as a paper, and I would suggest reading these for further information.
====
endif::backend-slidy[]

== How do you continuously integrate your ontology?

* We can test ontologies with standard frameworks
* These can run directly from leiningen
* This workflow allows the use of standard CI environment with no changes
* We use github/travis-CI
* Note, iff you import ontologies via URI, you may not get a repeatable build.

ifndef::backend-slidy[]
[NOTE]
====
Once you can test, then you can continuous integrate. We do this with
Travis-CI which is nice and it supports Clojure and Leiningen out of the box
(er, cloud). It also continuously integrates with the software environment
(including tawny). You can reason on there as well (tawny works headless just
fine).

If you import ontologies via URI you are totally dependent on them being
stable or you will not get a repeatable build. It's probably better to import
ontologies via their version IRI anyway to ensure this, although it's not
widely done.
====
endif::backend-slidy[]


== What about advanced documentation for Ontologies?

* Tawny-OWL ontologies are readable text
* It is possible to embed rich readable comments
* Also can use literate programming tools
* noweb, or org-mode use traditional approach
* I have also developed "lentic" which integrates with editor

ifndef::backend-slidy[]
[NOTE]
====
OWL raw does allow documentation but it's poor. With annotation properties you
have no structure at all unless you use microsyntax. Moreover most annotations
are sets -- so no order.

We have been experimenting heavily with literate programming tools. I started
this quite a few years back, but they now work well, and we have built a
specialised tool called "lentic".
====
endif::backend-slidy[]


== How do I collaborative develop by ontology?

* The same was as all software
* Version control for asynchronous, fork and merge with git
* Collaborative chat use gerrit, or skype
* Synchronous editing, try floobits, a web editor

ifndef::backend-slidy[]
[NOTE]
====
Collaborative development is not a new requirement and is, in fact, the
default for some environments. Just use existing tools. Git if you want
asynchronous development, or floobits, or even a virtual machine, tmux and
Emacs in the console. What ever.

The point is, it's not a problem for tawny. It's a problem for many software
engineers world-wide and they have provided some very, very slick solutions.
====
endif::backend-slidy[]


== Can I internationalise my ontology?

* Can add internationalised labels

[source,lisp]
----
(label "Ciao" "it")
----

* Can define internationalised function calls

[source,lisp]
----
(defn etichetta [l]
  (label l "it"))
----

* Can use `tawny.polyglot` to use property bundles

ifndef::backend-slidy[]
[NOTE]
====
It's very easy. Tawny programmability means that you can also support a
default language if you chose to, and have your ontologists use their own
native language for all parts of the system. Our example of `etichetta` above
is one of the complicated examples -- tawny has to know the default language
also. In most cases, we could just define aliases (see `tawny.english` for
examples). `tawny.polyglot` uses property bundles which I believe integrate well
with most machine-supported translation environments.
====
endif::backend-slidy[]

== Can I scaffold my ontology from existing source

* Can "import" ontology terms from spreadsheet, XML or a database
* Can work over existing source
* Therefore can generate core of ontology
* And expand it with manually annotated cross links

* See ICBO 2015 paper - http://arxiv.org/abs/1505.04114
* See Phillip Lord's blog - http://www.russet.org.uk/blog/3076

== What happens if the labels of read ontologies change

* OBO ontologies use numeric IDs
* These are unreadable, so we syntactically transform labels
* If label changes (but ID remains the same) is a problem
* Can use `tawny.memorize` to remember mappings
* Which adds aliases to those now missing (with optional "deprecated" warnings)

ifndef::backend-slidy[]
[NOTE]
====
The problem here is that we have to do something to get readable names for OBO
style ontologies. But we are now using a part of the OBO style ontology that
is open to change with, perhaps, fewer guarantees than for identifiers.

Tawny has support for this. It's solves the problem by saving the mapping that
it creates between a label and a URI. If the URI remains, but the label
disappears than tawny adds an alias and deprecation warning.
====
endif::backend-slidy[]


== How do you convert an existing ontology to Tawny-OWL

* `tawny.render` can perform a syntactic transformation
* Given OWL provides equivalent Clojure code
* Used interactively to provide documentation
* Can be used to port an ontology
* Currently "patternising" ontology is manual
* See Jennifer Warrender's PhD thesis where she did this with SIO

ifndef::backend-slidy[]
[NOTE]
====
We do have a methodology for doing this. We can render most of the ontology
automatically, which provides the basis for this kind of port. But actually
making use of the advanced features of tawny (like patterns or the
`as-subclasses` functionality) is manual. In general, at least some of this
will be necessary although it can be done manually.
====
endif::backend-slidy[]

== How Fast is Tawny

* For raw, un-patternised ontology tawny takes about 2x as reading OWL/XML
* Tested by rendering and load GO
* About 56Mb of lisp
* Loads in about 1min
* Most of excess time is in parsing, (Clojure also compiles)
* Patternised ontology would involve less parsing

ifndef::backend-slidy[]
[NOTE]
====
In short, it's fast enough that you are probably never going to notice it. We
cannot currently test how much difference the patternisation would make, but it
might be substantial.

It is also worth noting that with an ontology the size of GO, iff it were
developed in Tawny, it would be unlikely to be single file. Interactively
(i.e. in the editor) you probably would not be loading the whole ontology most
of the time anyway.
====
endif::backend-slidy[]

== Can I integrate more tightly with Protege?

* We have built a GUI shell into Protege
* Can also use Protege to open a Clojure REPL via a socket
* Protege then displays directly the state of Tawny
* Good for demonstration
* But a little flaky for normal use
* Having Protege reload an OWL file easier


https://vimeo.com/79395370

ifndef::backend-slidy[]
[NOTE]
====
This should work nicely and it does, but the truth is that at the moment a
REPL opened inside Protege hangs periodically and I do not know exactly why; I
suspect it is that Protege is not entirely happy with having it's data
structures changed underneath it, but I have not had the leisure to debug
this yet.

In our hands, the auto-reload function works well. I tend to render first to
OMN and look at that. Tawny also has a documentation capability which shows
you the "unwound" definition of terms. And then finally I use Protege after
that.
====
endif::backend-slidy[]


== How does Tawny affect dependency management with ontologies?

* Clojure uses maven dependency management
* We can now publish ontologies as maven artefacts
* And specify dependencies, with versions, and tooling
* Can publish on Maven central or Clojars (no infrastructure to maintain!)
* Separates ID and download location -- disobeys LOD principles
* But fulfils, SLOD principles.

ifndef::backend-slidy[]
[NOTE]
====
Clojure uses maven dependency management. As a tawny ontology is just
a piece of Clojure, we can use the same mechanism with tawny
ontologies also. Which means that we can specify ontological
dependencies also. This means we can specify version ranges (OWL
doesn't allow this to my knowledge). And we can reuse tooling. We
can use Leiningen to show us a dependency graph, we can look for
version conflicts, and we can exclude duplicates from the transitive
closure.

Interestingly, we can also publish our ontology independently from our IDs.
So, we can get someone else to maintain all the infrastructure for deployment
(including of multiple versions) without having to adopt their identifiers
(like bioportal).

This rather breaks the Linked Open Data (LOD) principles, of course which says
that IDs should resolve. Using maven dependencies we don't need this at
all. But it fulls the SLOD (significant load of dependencies) principle which
says if your software has lots of dependencies *and* lots of different people
maintaining the infrastructure for their availability it is going to break all
the time.

Thanks to Helen Parkinson for inspiring (a slightly different version) of the
SLOD acronym.
====
endif::backend-slidy[]

== Can I link ontologies into software?

* OWL API objects become first class entities in Clojure
* Can refer to them directly
* We integrated Overtone -- a music generation system
* Added in Tawny-OWL and the Music Ontology
* We now have software that plays a tune
* And provides OWL metadata about that tune
* More to investigate here.

ifndef::backend-slidy[]
[NOTE]
====
One of the great unexplored areas of Tawny at the moment is how much value we
can get embedding an ontology into software. We did have a very short project
integrating a semantic system (tawny) with a music generation system. This
works and was fun. I think there is a lot of scope for research in this
area yet.
====
endif::backend-slidy[]

== What's this `:super`? why not `:subclass`?

* Manchester syntax uses `SubClassOf:`
* Tawny uses `:super` for the same purpose!
* Confusing!
* Manchester syntax is actually backward
* In tawny, all frames are `A has :frame B`
* In Manchester `A is a SubClassOf: B`
* http://www.russet.org.uk/blog/2985

ifndef::backend-slidy[]
[NOTE]
====
I made this change very carefully and was very reticent about it: not least
because it made my main user of Tawny at the time (Jennifer Warrender) change
all of their existing code. But I had really confusing code inside Tawny where
my `add-subclass` functions had backward semantics to all the others.

I changed from ":subclass" to a more plain ":super" at the same time. This
opens up a slight risk because object-property has the same frame but for a
different purpose. I do not worry about this too much because other tools will
pick up, for example, the use of a class as a super-property.
====
endif::backend-slidy[]

== How do OBO identifiers work?

* The mapping is stored in a file
* The `obo-restore-iri` line above reads this file
* If a symbol has no mapping, we use the "pre-iri" form.

== How OBO Identifiers work

* The mapping file is generated
* Human readable, and line-orientated
* Deterministically ordered
* Will version!
* Uses EDN format.

[source,notlisp]
----
("ro"
 "http://purl.obolibrary.org/obo/EXAM_000001"
 "G"
 "http://purl.obolibrary.org/obo/EXAM_000002"
 "F"
 "http://purl.obolibrary.org/obo/EXAM_000003")
----

ifndef::backend-slidy[]
[NOTE]
====
The mapping file has been designed to work with version control, because it
needs to be shared between all developers. Although it is a generated file, it
is source code, since it cannot be recreated from fresh (not in the same order
anyway).

EDN format is a Clojure thing. It's basically a Clojure read syntax.
====
endif::backend-slidy[]

== How OBO Identifiers work

* Stable pre-iri's
* No need for a server such as URIgen

[source,lisp]
----
this stores any new IDs we have created
(comment
  (tawny.obo/obo-store-iri obo "./src/tawny/tutorial/whats_in_a_name.edn"))
----

ifndef::backend-slidy[]
[NOTE]
====
While the preiris are automatically created, if we choose they can be made
stable by simply saving them into the file with the form above. This can be
safely done every time the file is evaluated, because the order is
deterministic, so it will cause no false diffs in versioning.

This is potentially useful if you are collaborating with others and want to
co-ordinate at pre-release time. It's not essential if others are using
tawny -- there is no need, since classes can be referred to by symbol.

There is a potential disadvantage. This creates an IRI (and entry in the file)
for every new entity created. Not a problem with Protege, but tawny is fully
programmatic. I can create 10^6 new classes in one line of code.

pre-iris all appear at the end of the EDN file!
====
endif::backend-slidy[]

== How OBO Identifiers work

* How to create permanent IDs
* Needs to be co-ordinated, since IDs are incremental
* Use version-control to co-ordinate
* One person, or as part of a release process

[source,lisp]
----
this coins permanent IDS, in a controlled process!
(comment
  (tawny.obo/obo-generate-permanent-iri
   "./src/tawny/tutorial/whats_in_a_name.edn"
   "http://purl.obolibrary.org/obo/EXAM_"))
----

ifndef::backend-slidy[]
[NOTE]
====
At some point, you need to coin new IDs that will become permanent. This has
to happen in a co-ordinated fashion. It could be done as part of release. Or
by bot during continuous integration.
====
endif::backend-slidy[]


== How OBO Identifiers work

* I think having no server is nice
* Reusing version control makes sense
* It's programmatic! You are free to disagree.

ifndef::backend-slidy[]
[NOTE]
====
How well would this workflow work in practice? Not sure. It would work for a
small number of developers. There are many tweaks that could be made for
different scales -- saving to multiple files, pre-iris in one place, perms in
another. No pre-iris at all. Use URIGen. Manually coin permanent IRIs as part
of quality control.

It's programmatic and easy to change.
====
endif::backend-slidy[]

== Do I have to conform to the no-use-before-define rule?

* It is possible not to use symbols
* The `iri-gen` function takes a string not a symbol!
* This string is the tawny name
* Consider the following

[source,lisp]
----
String building!
(defontology s)

(owl-class "J" :ontology s)
(object-property "r" :ontology s)
(owl-class "K"
           :ontology s
           :super (owl-some "r" "J"))
----

ifndef::backend-slidy[]
[NOTE]
====
We can do without symbols and instead use just strings. Note that we also have
to switch functions `owl-class` instead of `defclass`.
====
endif::backend-slidy[]

== What are Tawny Names?

* These forms do *NOT* define symbols
* This *WILL NOT* work
* Neither `r` nor `J` have been defined

[source,lisp]
----
(comment
  (owl-class "L"
             :ontology s
             :super (owl-some r J)))
----

== Tawny Names

* Danger!
* Consider this statement.
* But we did not define "L"
* But we have used it.

[source,lisp]
----
(owl-class "M"
           :ontology s
           :super "L")
----

* And so, it becomes defined

[source,omn]
----
Class: s:M
    SubClassOf:
        s:L

Class: s:L
----

ifndef::backend-slidy[]
[NOTE]
====
The use of strings means that we can define things without the tawny-name
being in "primary position". It just happens. You need to be careful.
====
endif::backend-slidy[]


== Why use strings?

* Partly, there for implementation
* But made public as string manipulation is easier
* Most useful for development

ifndef::backend-slidy[]
[NOTE]
====
The main reason that I have left this in place is for use as an API. Clojure
allows full manipulation of symbols like most lisps, but it's a bit of a pain.
It's not possible, for example, to concatenate two symbols to make a longer
one (or rather, they need to be converted to strings, then concat'd then
converted back again). And the creation and interning of new symbols as
variables requires the use of macros rather than normal functions.

Having said that, tawny does offer some facilities to help with this process

 - `tawny.owl/intern-owl-entity`
 - `tawny.owl/intern-owl-string`
 - `tawny.owl/defentity`
 - `tawny.owl/intern-owl-entities`
 - `tawny.util/quote-word`
 - `tawny.util/name-tree`

We will see a few of these later.
====
endif::backend-slidy[]

== How do we create a new symbol with the `amino-acid` syntax?

* If we want to create a new symbol Tawny-OWL provides `defentity`
* It does a few other things as well

[source,lisp]
----
(defentity defaminoacid
  "Defines a new amino acid."
  'amino-acid)
----

ifndef::backend-slidy[]
[NOTE]
====
In fact, `defclass`, `defoproperty` and the rest are all defined in
this way.  This is a common enough thing to want to do, that I made
this macro public. It is an easy way, for instance, to add new frames
or set default values for existing frames, or to define patterns.

`defentity` does one or two other things as well, chiefly adding
metadata to the var created. If you don't know what this means (unless
you know Clojure you probably wont) then it really isn't important.
====
endif::backend-slidy[]

