
== Introduction

* Tawny-OWL is fully programmatic environment for Ontology Development
* Presents a different model of ontology development
* Very powerful
* Allows reuse of commodity tooling


== Today

* Some taught material
* Some "follow-by-leader"
* Plenty of time for questions
* A flexible tail


ifndef::backend-slidy[]
[NOTE]
====

Today, we will have some taught material, particularly at the beginning and
the end, where I need to describe parts of the system, some practical time
where we build a small ontology using tawny. Then I have a reasonably flexible
tail where I try and address questions that people have. Also, there is a
degree of guesswork into how much material I can get into the time available,
which this helps to address.

I do not have time to describe all of the features of tawny, nor give a full
tutorial.
====
endif::backend-slidy[]



== Today

* Attempted to make decoupled
* Aware that people will come in and out
* Probably not be entirely successful at this.
* Gets more programmatic as we go on
* Will not explain all of the programming

ifndef::backend-slidy[]
[NOTE]
====

Although the tutorial does "build" I have tried to make it as loosely coupled
as possible, although the truth be told, I have probably not been entirely
successful at this.

The latter half requires more programming knowledge, and there is probably
little that I can do about this. I will skip over what some of it means, in
the hope that those who care can go back later and look it up. I do not want
this to become a Clojure tutorial.

====
endif::backend-slidy[]


== Knowledge Prerequisites

* Required
** Basic knowledge of ontologies
** Basic knowledge of OWL
** Basic knowledge of biology (amino-acids!)
** For last 1/3: Basic Programming Knowledge

* Not Required
** Knowledge of Clojure
** Knowledge of OWL API
** Knowledge of Tawny-OWL


== Outcomes

* Understand the motivation behind Tawny
* Understand and use basic Clojure infrastructure
* Build a basic ontology with Tawny
* Understanding pattern usage within Tawny
* Implementing a pattern
* Extending Tawny locally


== Secondary Outcomes

* Understand how to repurpose software tooling for ontologies


== Notes on Notes

* All materials are available
* These slides (2015_swat4ls.html)
* As a book with lecture notes (2015_swat4ls_book.html)
* Same thing as PDF (but less well checked!).

http://homepages.cs.ncl.ac.uk/phillip.lord/download/tawny/icbo_2015

