== Tawny-OWL Tutorial

* The source for these slides
* All the sample code
* `git clone https://github.com/phillord/tawny-tutorial.git`
* Or download https://github.com/phillord/tawny-tutorial/releases

ifndef::backend-slidy[]
[NOTE]
====

Now a quick detour i.e. pre-requisites.

All resources for this tutorial can be found on the git repository;
link and command provided.

You will find the documentation for Clojure code embedded in the
Clojure files themselves. This "literate programming" was accomplished
using Phil's "lenticular" tool. Phil will be talking about this in his
paper talk @ 15:40 tomorrow.

====
endif::backend-slidy[]

== Other Technical Pre-Requisites

* JVM
* Leiningen
* https://github.com/phillord/tawny-tutorial
* Protege

ifndef::backend-slidy[]
[NOTE]
====

For a hands-on approach to this tutorial these technical
pre-requisites will be needed to be installed/downloaded.

See pre-requisites.adoc

====
endif::backend-slidy[]

== Or: the alternative

* Protege or text editor
* All generated ontologies
* http://homepages.cs.ncl.ac.uk/jennifer.warrender/swat4ls_2015/ontologies/

ifndef::backend-slidy[]
[NOTE]
====

Only Protege needs to be installed.

Download generated ontologies are available; see link.

====
endif::backend-slidy[]

